# Generated by Django 2.0.4 on 2018-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tokenid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tokenId',
        ),
        migrations.AddField(
            model_name='image',
            name='photoToken',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
