# Generated by Django 2.0.4 on 2018-06-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20180620_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='txHash',
            field=models.CharField(default='pending', max_length=500),
        ),
    ]
